@startuml

rectangle "System Boundry" {
    usecase (withdraw cash) as UC1
    usecase (deposit cash) as UC2
    usecase (check balance)
    usecase (check atm balance)
}
:user: --> UC1
:user: --> UC2

@enduml
