@startuml

package "System Boundry" {
    usecase (withdraw cash) as WC
    usecase (deposit cash) as DC
    usecase (check balance)
    usecase (check atm balance)
}
:user: --> WC
:user: --> DC

@enduml
