@startuml

left to right direction
rectangle "System Boundry" {
    usecase "withdraw cash" as UC1
    usecase "deposit cash" as UC2
    usecase "check balance" as UC3
    usecase "check atm balance" as UC4
}
:user: --> UC1 : enters ammount
:user: --> UC2 : enters cash

@enduml
